#!/usr/bin/env python3

import os
import stat
from mfutil import mkdir_p

SWITCH_DIRECTORIES =\
    os.environ.get("MFDATA_INTERNAL_PLUGINS_SWITCH_DIRECTORIES")

for directory in SWITCH_DIRECTORIES.split(';'):
    path = os.path.join(
        os.environ.get("MFDATA_DATA_IN_DIR"),
        directory)
    res = mkdir_p(path)
    if res:
        st = os.stat(path)
        os.chmod(path, st.st_mode | stat.S_IWGRP)
