#!/bin/bash

_make_directory_observer_conf >"${MFMODULE_RUNTIME_HOME}/tmp/config_auto/directory_observer.ini"

if ! test -s "${MFMODULE_RUNTIME_HOME}/tmp/config_auto/directory_observer.ini"; then
    echo "ERROR : can't make directory_observer configuration file"
    exit 1
fi

python3 <<EOF
import os
from opinionated_configparser import OpinionatedConfigParser
from mfutil import mkdir_p

parser = OpinionatedConfigParser()

parser.read("%s/tmp/config_auto/directory_observer.ini" % os.environ['MFMODULE_RUNTIME_HOME'])

for section in parser.sections():
    try:
        directory = parser.get(section, 'directory')
    except:
        continue
    mkdir_p(directory, nodebug=True, nowarning=True)
EOF
