#!/bin/bash

_make_directory_observer_conf >"${MODULE_RUNTIME_HOME}/tmp/config_auto/directory_observer.ini"

if ! test -s "${MODULE_RUNTIME_HOME}/tmp/config_auto/directory_observer.ini"; then
    echo "ERROR : can't make directory_observer configuration file"
    exit 1
fi

python3 <<EOF
import os
from configparser_extended import ExtendedConfigParser
from mfutil import mkdir_p

config = os.environ.get('MFCONFIG', 'GENERIC')
parser = ExtendedConfigParser(config=config, strict=False, inheritance='im', interpolation=None)

parser.read("%s/tmp/config_auto/directory_observer.ini" % os.environ['MODULE_RUNTIME_HOME'])

for section in parser.sections():
    try:
        directory = parser.get(section, 'directory')
    except:
        continue
    mkdir_p(directory, nodebug=True, nowarning=True)
EOF
